import './style.css'

type Room={id:string; title:string; subtitle:string; cover:string; photos:string[]}
const rooms:Room[]=[
 {id:'coffee-book',title:'Coffee & Book',subtitle:'一段关于安静、阅读与午后光线的记录',cover:'/photos/1-coffee-book-cover.png',photos:[]},
 {id:'city',title:'城市漫游指南',subtitle:'沿着街角、橱窗和晚风行走',cover:'/photos/2--cover.png',photos:[]},
 {id:'bride',title:'落跑新娘',subtitle:'一场没有按剧本发生的婚礼',cover:'/photos/3--cover.png',photos:[]},
 {id:'butterfly',title:'黄晶眼蝶',subtitle:'在野地里寻找轻盈的翅膀',cover:'/photos/4--cover.png',photos:[]},
 {id:'her',title:'美丽的她',subtitle:'关于凝视、距离与被看见',cover:'/photos/5--cover.png',photos:[]}
]
const files:Record<string,string[]>={'coffee-book':['1.jpg','2.jpg','3.jpg','4.jpg','5.jpg','6.jpg','7.jpg','8.jpg','9.jpg','10.jpg','11.jpg','12.jpg','13.jpg','14.jpg','15.jpg'],'city':['1.jpg','2.jpg','3.png','4.jpg','5.png','6.png','7.png','8.png','9.png','10.jpg','11.jpg','12.jpg','13.jpg','14.jpg','15.jpg','16.jpg','17.jpg','18.jpg','19.jpg','20.jpg','21.png','22.png','23.png','24.png','25.png','26.png','27.jpg','28.png'],'bride':['1.jpg','2.jpg','3.jpg','4.jpg','5.jpg','6.jpg','7.jpg','8.jpg','9.jpg','10.jpg','11.jpg','12.jpg','13.jpg','14.jpg','15.jpg','16.jpg','17.jpg','18.jpg','19.jpg','20.jpg','21.jpg','22.jpg','23.jpg','24.jpg','25.jpg','26.jpg','27.jpg','28.jpg','29.jpg','30.jpg','31.jpg','32.jpg','33.jpg','34.jpg'],'butterfly':['1.jpg','2.jpg','3.jpg','4.jpg','5.jpg','6.jpg','7.jpg','8.jpg','9.jpg','10.jpg','11.jpg','12.jpg','13.jpg','14.jpg','15.jpg','16.jpg','17.jpg','18.jpg','19.jpg','20.jpg','21.jpg','22.jpg','23.jpg','24.jpg','25.jpg','26.jpg','27.jpg','28.jpg','29.jpg','30.jpg'],'her':['1.jpg','2.jpg','3.jpg','4.jpg','5.jpg','6.jpg','7.jpg','8.jpg','9.JPG','10.jpg','11.jpg','12.jpg','13.jpg','14.JPG','15.jpg','16.jpg','17.jpg','18.jpg','19.jpg','20.jpg','21.jpg','22.jpg','23.jpg','24.JPG','25.JPG','26.jpg','27.jpg','28.jpg','29.jpg','30.jpg','31.jpg','32.jpg','33.jpg','34.jpg','35.jpg','36.jpg','37.jpg','38.jpg','39.JPG']}
rooms.forEach(r=>{r.photos=files[r.id].map((f:string)=>`/photos/${r.id}/${f}`);r.photos.sort((a,b)=>{const seq=(x:string)=>{const tail=x.match(/(\d+)(?=\.[^.]+$)/)?.[1]||'0';if(tail==='2'){const m=x.match(/(\d+)_2\.[^.]+$/);return Number(m?.[1]||tail)}return Number(tail)};return seq(a)-seq(b)})})
const app=document.querySelector<HTMLDivElement>('#app')!
app.innerHTML=`<div class="grain"></div><header><div class="mark">M / 05</div><div class="hint">五次拍摄 · 五段记忆</div><button class="about">重看开场</button></header><main><section class="rooms"><div class="section-label">SELECT A ROOM <span>01 — 05</span></div><div class="room-grid">${rooms.map((r,i)=>`<article class="room room-${i+1}" data-room="${r.id}"><div class="sketch">${String(i+1).padStart(2,'0')}</div><div class="cover"><img src="${r.cover}" alt="${r.title}代表图"></div><div class="room-meta"><h2>${r.title}</h2><p>${r.subtitle}</p><span class="enter">ENTER ROOM ↗</span></div></article>`).join('')}</div></section></main><footer><span>© 2026 MY PHOTO ROOMS</span><span>BUILT WITH MEMORY & LIGHT</span></footer><div class="modal" aria-hidden="true"><button class="close">CLOSE ×</button><div class="modal-head"><div class="modal-index"></div><h2 class="modal-title"></h2><p class="modal-sub"></p></div><div class="book-stage"><button class="book-nav prev">← PREV</button><div class="photo-wall"></div><button class="book-nav next">NEXT →</button></div><div class="page-count"></div></div>`
const modal=document.querySelector<HTMLElement>('.modal')!, wall=document.querySelector<HTMLElement>('.photo-wall')!, count=document.querySelector<HTMLElement>('.page-count')!, title=document.querySelector<HTMLElement>('.modal-title')!, sub=document.querySelector<HTMLElement>('.modal-sub')!, idx=document.querySelector<HTMLElement>('.modal-index')!
let activeRoom:Room|null=null;let activePage=0;function renderPage(){if(!activeRoom)return;wall.querySelectorAll<HTMLElement>('.shot').forEach((el,i)=>el.classList.toggle('page-active',i===activePage));count.textContent=`PAGE ${String(activePage+1).padStart(2,'0')} / ${String(activeRoom.photos.length).padStart(2,'0')}`}function openRoom(id:string){const r=rooms.find(x=>x.id===id)!;activeRoom=r;activePage=0; title.textContent=r.title; sub.textContent=r.subtitle; idx.textContent=`ROOM ${String(rooms.indexOf(r)+1).padStart(2,'0')}`; wall.innerHTML=r.photos.map((p,i)=>`<figure class="shot shot-${i+1}"><img src="${p}" alt="${r.title} ${i+1}"><figcaption>${String(i+1).padStart(2,'0')} / ${r.title}</figcaption></figure>`).join(''); renderPage();modal.classList.add('is-open'); modal.setAttribute('aria-hidden','false'); document.body.classList.add('locked')}
const roomEls=[...document.querySelectorAll<HTMLElement>('.room')];let entryPage=0;const grid=document.querySelector<HTMLElement>('.room-grid')!;grid.insertAdjacentHTML('beforebegin','<div class="entry-book-controls"><button class="entry-prev">←</button><span class="entry-count"></span><button class="entry-next">→</button></div>');const entryCount=document.querySelector<HTMLElement>('.entry-count')!;function showEntryPage(next:number){entryPage=(next+roomEls.length)%roomEls.length;roomEls.forEach((el,i)=>el.classList.toggle('entry-active',i===entryPage));entryCount.textContent=`${String(entryPage+1).padStart(2,'0')} / 05`;grid.classList.remove('page-turn');void grid.offsetWidth;grid.classList.add('page-turn')}roomEls.forEach(el=>el.addEventListener('click',()=>openRoom(el.dataset.room!)));document.querySelector('.entry-prev')!.addEventListener('click',()=>showEntryPage(entryPage-1));document.querySelector('.entry-next')!.addEventListener('click',()=>showEntryPage(entryPage+1));showEntryPage(0)
document.querySelector('.prev')!.addEventListener('click',()=>{if(activeRoom){activePage=(activePage-1+activeRoom.photos.length)%activeRoom.photos.length;renderPage()}});document.querySelector('.next')!.addEventListener('click',()=>{if(activeRoom){activePage=(activePage+1)%activeRoom.photos.length;renderPage()}});document.querySelector('.close')!.addEventListener('click',()=>{modal.classList.remove('is-open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('locked')})
const siteMain=document.querySelector<HTMLElement>('main')!;
const welcome=document.createElement('section');welcome.className='welcome';welcome.setAttribute('aria-label','欢迎来到摄影影集');welcome.innerHTML=`<div class="welcome-art" aria-hidden="true">${rooms.map((r,i)=>`<img src="${r.cover}" alt="" style="--i:${i};--tilt:${(i-2)*9}deg;--offset:${(i-2)*56}px">`).join('')}</div><p class="welcome-kicker">A LITTLE BOOK OF MEMORIES</p><h1>把瞬间，<br><em>轻轻翻开。</em></h1><button class="welcome-enter">翻开影集 <span>↗</span></button><p class="welcome-note">五次拍摄，收藏在这里。</p>`;document.body.append(welcome);
function showWelcome(){welcome.hidden=false;welcome.classList.remove('leaving');siteMain.inert=true;document.body.classList.add('welcoming');welcome.querySelector<HTMLButtonElement>('button')!.focus()}
welcome.querySelector('button')!.addEventListener('click',()=>{welcome.classList.add('leaving');window.setTimeout(()=>{welcome.hidden=true;siteMain.inert=false;document.body.classList.remove('welcoming');window.scrollTo(0,0);document.querySelector<HTMLButtonElement>('.entry-next')!.focus()},window.matchMedia('(prefers-reduced-motion: reduce)').matches?0:700)});
document.querySelector('.about')!.addEventListener('click',showWelcome);showWelcome();
window.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelector<HTMLButtonElement>('.close')!.click()})






